apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
  namespace: realworld-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: ${BACKEND_IMAGE_TAG}
          envFrom:
            - secretRef:
                name: backend-secrets
