apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: realworld-app
spec:
  type: ClusterIP       
  selector:
    app: backend
  ports:
    - port: 3000        
      protocol: TCP
      targetPort: 3000  
