apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 12h
  chartRef:
    kind: OCIRepository
    name: cert-manager
  values:
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: cert-manager@realworld-app-483521.iam.gserviceaccount.com
    crds:
      enabled: true
    config:
      enableGatewayAPI: true
