version: "3.9"

services:
  frontend:
    image: ghcr.io/nospooksallowed/realworld-fullstack-app:frontend-latest
    depends_on:
      - backend
      - postgres_db
    ports:
      - "80:8080"
  backend:
    image: ghcr.io/nospooksallowed/realworld-fullstack-app:backend-latest
    env_file: 
      - ./backend/.env
    depends_on:
      migrate:
        condition: service_completed_successfully

  migrate:
    image: ghcr.io/nospooksallowed/realworld-fullstack-app:backend-latest
    env_file:
      - ./backend/.env
    depends_on:
      postgres_db:
        condition: service_healthy
    command: npm run migrate:prod
  postgres_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
