apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: realworld-app
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL215dXNlcjpteXBhc3N3b3JkQHBvc3RncmVzOjU0MzIvZGIK 
  JWT_SECRET: WlpUWG5KVnZNYnNXR0FNVmJEQXg2K0Y5YjBlSTZYdUMvcFVIelN4QnRPV3RnaDh3cG9MQWlET1RyV3VXQWF6bVV0Z2RXeXh3alIzakIzODRvYkVXa0E9PQo=
