apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy
  namespace: envoy-system
spec:
  interval: 24h
  url: oci://registry-1.docker.io/nomadxynta/envoy-proxy-gateway-helm-patched
  ref:
    tag: v1.7.1
