apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: backend-container
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          envFrom:
            - secretRef:
                name: backend-secrets
