apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrate
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend-migrate
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          command: ["npm", "run", "migrate:prod"]
          envFrom:
            - secretRef:
                name: backend-secrets
