apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.backend.service.type }}       
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.service.port }} 
      protocol: TCP
      targetPort: {{ .Values.backend.service.targetPort }}
