apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
    namespace: realworld-app
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:NxcHPTuk2Svcap9xSXlTW9ETZBUCHa2PkWkopR/Wl0i8sHzdsvd3NmHZNsbUgdZvl0FFg0Fa+euPoD+iOIQGHbIrUYPw8DMJwxI6LnI=,iv:Aeoqa5ieBx/QjtuIb6veE9N8y5rrxBKZU0bmXsVfIZk=,tag:y66F6iFhpIMCIywk/VhYuQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:+c2o4yWZ8qlK+jYmEYfWhMYWBDKOtkZTedz3p5mDBrlWFhYAaX6RFt+Rw+850llP9zT26sIagMZw6nsBcfeFKXkNZS+Mpsu/Wh57p04SsJg9npi5YD8FpQ==,iv:PpvD/BvCXQfyhd/azIFNQPPnNvBIGytAlt1aJzgt5C8=,tag:PAto4drDeWQTF047yx1i7w==,type:str]
sops:
    lastmodified: "2026-03-29T19:10:49Z"
    mac: ENC[AES256_GCM,data:Xp8sB4sNNGqysH52LoIbAXIW/GjQu3QfsUY/fKT5VlnhtOBrMEdFodCo4jj/FSWHEaq/RLQgELZ+7cYfBivC/i/EEvXFY3HeKDVBAH4S/aHT5tJrFBaaNB2QxmGu2JX5NX6LGM9JaqBtjRPylypqFzalBX1BpM4fScKxVNwq9Jw=,iv:dLVOeeOour2paSf4dckvYhK6ZdIyzfnlDC6XhMWBSEc=,tag:otU7U7zszdPTI38tKwU11A==,type:str]
    pgp:
        - created_at: "2026-01-03T03:00:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA07bJ8Xh3yEwAQ/+KN4e//+7gqRSOgUJ6Hx/iZ5Is4mkqdoEHFS35XiKZHmF
            N3X+mR5TxawnNP1JNy+yoLHjMnkdwiqA8ApHEf2z0KA+iS1s146r34oFjmHuS8kb
            xC3so8J5zIbzLGk5XQyJsRY/KpkFdQ4CMGt84mJOfmRNJU0FxLgQOtqKaXLT+o3P
            n9O237XK7p/nniSi7Cy9efQOfvIr9EitP7tynXE0zoPCp6bHVoS05ieE6vQOEoyP
            c0P8r+etXEb4BYsj54Ctv2xigOfTxjqHUEzW6KTU+VnVqz/ELVYdli0fAiDxpa+x
            tsoxh/bwjuL1v5RU6gt4lB3adn3VmWEJc5e4IwkEkqyZP/oGYUupjKJkALug31te
            AVl6iIq8uppTNQApQdss4irbErBFiY4w4+rMxLPyUSUPdwYSPM6rltiqBpNpfOhz
            WzO3mXyC/LoU9eYcABOVwnUbPSeZUZC+TzL2hR1wQQBcL7LARGm65Vhnu203HicE
            kCHR+ZD/fa7ZrR0l2SQXOjGcQpg4Q5B+zyUlo2QVKQhWNspUMVwB6SgH3OVNcwgj
            DRYnKMQNIfpcx6Jt+jFD0RzKYSbsLzaX7UboBzzcXbySCkcs+vr8mHWPoP0X5VSl
            GSQ+tBqfkpcZOi/Zx2xAKxOsJApXYhaBxU1mZcrnz+n+qpK20gi68mafPg4WM2XS
            XgERvMbzX/E7SfuYIdl0HeMt/SP8mIQwe8WcBZY40unpPbXfqnXkvVAoCxR30PRv
            tvqR/nKIIDx+RQDtQdS9vBKTZhNHV7Vj2zmQCHaqSvGDjlysDLUcCd6pep2OHDQ=
            =1KpL
            -----END PGP MESSAGE-----
          fp: A3C5A8D20CA0C35395CB083EEC6B00FEF5418E18
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
