apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: realworld-app
spec:
  type: ClusterIP       
  selector:
    app: frontend
  ports:
    - port: 80       
      protocol: TCP
      targetPort: 8080 
