apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrate
  namespace: realworld-app
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: ${BACKEND_IMAGE_TAG}
          command: ["npm", "run", "migrate:prod"]
          envFrom:
            - secretRef:
                name: backend-secrets
